"""Create books table

Revision ID: a218e2916a5d
Revises: 
Create Date: 2026-02-17 23:50:23.167226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a218e2916a5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.UUID(), nullable=False, comment='Уникальный идентификатор книги (UUID)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Название книги (до 500 символов)'),
    sa.Column('author', sa.String(length=300), nullable=False, comment='Автор книги (до 300 символов)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Год издания'),
    sa.Column('genre', sa.String(length=100), nullable=False, comment='Жанр книги (до 100 символов)'),
    sa.Column('pages', sa.Integer(), nullable=False, comment='Количество страниц'),
    sa.Column('available', sa.Boolean(), nullable=False, comment='Доступна ли книга для выдачи'),
    sa.Column('isbn', sa.String(length=20), nullable=True, comment='Международный стандартный книжный номер (до 20 символов)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Полное описание книги'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='Дополнительные данные в формате JSON (издательство, серия, т.д.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Время последнего обновления записи'),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_available'), 'books', ['available'], unique=False)
    op.create_index(op.f('ix_books_book_id'), 'books', ['book_id'], unique=False)
    op.create_index(op.f('ix_books_genre'), 'books', ['genre'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_index(op.f('ix_books_year'), 'books', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_year'), table_name='books')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_genre'), table_name='books')
    op.drop_index(op.f('ix_books_book_id'), table_name='books')
    op.drop_index(op.f('ix_books_available'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
